name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  float-http-server:
    uses: gowithfloat/github-workflows/.github/workflows/dotnot_test.yml@main
    secrets: inherit
