name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  float-http-server:
    uses: gowithfloat/Float.FileDownloader/.github/workflows/test.yml@main
    secrets: inherit
